server:
  port: 8888

spring:
  rabbitmq:
    host: 114.215.211.160
    username: admin
    password: 123456
    port: 5672

  redis:
    host: 114.215.211.160
    port: 6379
    password: 352445205

  application:
    name: zyn-demo
